---
dmd_version: '2.066'
elixir_version: '0.14.0'
cask_version: '0.7.0'
go_version: '1.3'
ghc_version: '7.8.3'
scala_version: '2.11.1'
jruby_version: '1.7.13'
scalastyle_version: '0.5.0'
rpmlint_version: '1.6'
