- name: Install prerequisites to add package repositories
  apt: name=python-apt state=present
- name: Add 3rd party repositories
  apt_repository: repo='{{item}}' update_cache=false state=present
  with_items:
    - ppa:cassou/emacs          # Stable Emacs 24.3
    - ppa:ubuntu-elisp/ppa      # Nightly Emacs trunk builds
    - ppa:hansjorg/rust         # Nightly Rust builds
    - ppa:ondrej/php5           # Recent PHP versions
    - ppa:plt/racket            # Racket
    - ppa:hvr/ghc               # Latest GHC and Cabal
    - ppa:ubuntu-toolchain-r/test # Latest GCC
    # Latest Erlang version
    - deb http://packages.erlang-solutions.com/debian precise contrib
    # CFEngine
    - deb http://cfengine.com/pub/apt/packages stable main
- name: Add keys for 3rd party repositories
  apt_key: url={{item}} state=present
  with_items:
    - http://packages.erlang-solutions.com/debian/erlang_solutions.asc
    - http://cfengine.com/pub/gpg.key
- name: Update cache after adding PPAs
  apt: update_cache=true
- name: Install language environments and package managers
  apt: name={{item}} state=latest install_recommends=false
  with_items:
    # Languages and package managers
    - cpanminus                   # For Perl packages
    - php-pear                    # For PHP packages
    - python2.7                   # For Python packages
    - python-pip
    - erlang                      # For Erlang
- name: Install additional dependencies
  apt: name={{item}} state=latest install_recommends=false
  with_items:
    - build-essential
    - unzip
    # For go get
    - git-core
    - mercurial
    # For food-critic
    - libxslt1-dev
    - libxml2-dev
    # For DMD
    - gcc-multilib
    - xdg-utils
    # For rpmlint
    - python-rpm
- name: Install syntax checker tools
  apt: name={{item}} state=latest install_recommends=false
  with_items:
    - asciidoc                    # asciidoc
    - cfengine-community          # cfengine
    - chktex                      # tex-chktex
    - cppcheck                    # c/c++-cppcheck
    - coq                         # coq
    - dash                        # sh-posix-dash
    - g++-4.8                     # c/c++-gcc
    - gfortran-4.8                # fortran-gfortran
    - gnat                        # ada-gnat
    - ghc-{{ghc_version}}         # haskell-ghc
    - hlint                       # haskell-hlint
    - lacheck                     # tex-lacheck
    - libxml2-utils               # xml-xmllint
    - lua5.2                      # lua
    - perl                        # perl
    - php5-cli                    # php
    - pmake                       # make
    - racket                      # racket
    - rust-0.11                   # rust
    - texinfo                     # texinfo
    - tidy                        # html-tidy
    - verilator                   # verilog-verilator
    - xmlstarlet                  # xml-xmlstarlet
    - zsh                         # sh-zsh
- name: Download DMD
  get_url: url=http://downloads.dlang.org/releases/2014/dmd_{{dmd_version}}.0-0_amd64.deb
           dest=/usr/src/dmd_{{dmd_version}}.0-0_amd64.deb
  ignore_errors: True
- name: Install DMD
  apt: deb=/usr/src/dmd_{{dmd_version}}.0-0_amd64.deb state=installed
  ignore_errors: True
- name: Make GCC 4.8 the default GCC
  alternatives : name={{item}} link=/usr/bin/{{item}} path=/usr/bin/{{item}}-4.8
  with_items:
    - gcc
    - g++
    - gfortran
