---
dependencies:
  - {role: language-ada}
  - {role: language-asciidoc}
  - {role: language-c_cxx}
  - {role: language-cfengine}
  - {role: language-chef}
  - {role: language-coffee}
  - {role: language-coq}
  - {role: language-css}
  - {role: language-d}
  - {role: language-elixir}
  - {role: language-erlang}
  - {role: language-fortran}
  - {role: language-go}
  - {role: language-haml}
  - {role: language-handlebars}
  - {role: language-haskell}
  - {role: language-html}
  - {role: language-javascript}
  - {role: language-json}
  - {role: language-less}
  - {role: language-lua}
  - {role: language-make}
  - {role: language-perl}
  - {role: language-php}
  - {role: language-puppet}
  - {role: language-python}
  - {role: language-racket}
  - {role: language-rpm}
  - {role: language-rst}
  - {role: language-ruby}
  - {role: language-rust}
  - {role: language-sass}
  - {role: language-scala}
  - {role: language-scss}
  - {role: language-sh}
  - {role: language-slim}
  - {role: language-tex}
  - {role: language-texinfo}
  - {role: language-verilog}
  - {role: language-xml}
  - {role: language-yaml}
