- name: Setup the Flycheck VM
  hosts: flycheck
  gather_facts: false
  vars:
    gem_executable: gem1.9.1
    go_executable: /usr/local/go/bin/go
    go_env:
      GOPATH: /usr/local/lib/go
    home: /home/vagrant
  vars_files:
    - vars/versions.yml
    - vars/mirrors.yml
  sudo: True
  tasks:
    - name: Configure locale
      copy: dest='/etc/default/locale' mode=0644 owner=root group=root
            content='LC_ALL=en_US.utf8\nLANG=en_US.utf8\n'
    - name: Add additional repositories
      apt_repository: repo='{{item}}' update_cache=false state=present
      with_items:
        - ppa:chris-lea/node.js
        - 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.4 main'
    - name: Add additional repo keys
      apt_key: url='{{item}}' state=present
      with_items:
        - http://llvm.org/apt/llvm-snapshot.gpg.key
    - include: tasks/packages.yml
    - name: Install additional packages
      apt: name={{item}} state=latest install_recommends=false
      with_items:
        - clang-3.4
        - ruby1.9.1
        - ruby1.9.1-dev
        - nodejs
        - openjdk-7-jre
    - name: Make Clang 3.4 the default Clang
      alternatives: name=clang link=/usr/bin/clang path=/usr/bin/clang-3.4
    - name: Install Emacs stable and snapshot
      apt: name={{item}} state=latest install_recommends=false
      with_items:
        - emacs24-nox
        - emacs-snapshot-nox
    - name: Make Emacs snapshot the default
      alternatives: name=emacs link=/usr/bin/emacs path=/usr/bin/emacs-snapshot
    - name: Put Haskell into $PATH
      copy: dest=/etc/profile.d/ghc.sh mode=0644 owner=root group=root
            content="export PATH=/opt/ghc/{{ghc_version}}/bin:$PATH\n"
    - include: tasks/perl.yml
    - include: tasks/pear.yml
    - include: tasks/npm.yml
    - include: tasks/go.yml
    - include: tasks/goget.yml
    - include: tasks/elixir.yml
    - include: tasks/cask.yml
    - include: tasks/eggs.yml
    - include: tasks/gems.yml
    - include: tasks/java.yml
    - include: tasks/rpm.yml
    - name: Automatically change to /flycheck directory on login
      lineinfile: dest="{{home}}/.bashrc" state=present
                  line="cd /flycheck" insertafter=EOF
